### ISSUE TITLE
Missing File issue - '../data/train/train2014/train_ImageNet_FisherVectors.mat'

### ISSUE THREAD

**Issue by Innovator545** [imatge-upc/vqa-2016-cvprw#2]
Hi

Thanks in advance for your time to look into the issue !!

I have been trying to understand and  use your Visual QA source code for my images.
I am able to successfully  compile the code for Model-6 after resolving few issues.
When the training part starts, i am getting the below error for one missing file -

IOError: [Errno 2] No such file or directory: '../data/train/train2014/train_ImageNet_FisherVectors.mat'

It appears that the Process/SourceCode/Steps for generating this missing file using training images is missing from the github repository.  Sorry if i am mistaken.

Kindly provide the Steps/Source code for the same 
OR 
Please guide if i am missing something here 
OR 
Kindly suggest any direction which will be helpful for me to generate train_ImageNet_FisherVectors.mat file.

I have extensively reviewed the code and also went through the thesis -
https://imatge.upc.edu/web/sites/default/files/pub/xMasuda-Mora_0.pdf

Kindly help.
I shall be very thankful to you.

Warm Regards,
Preetinder Singh

**Comment by issey173** [comment]
Hi!

That is correct, the precomputed visual features of the dataset are missing. This is due to the fact that the file size is too big for GitHub to store it, so when we try to push the file the process breaks.

This code was developed focusing on our participation to the VQA Challenge but we are now modifying this project so it's actually more modular and reusable (do not depend on these precomputed visual features for example). 

If you are in a hurry I can email you the needed files in order to be able to do a full execution of the code or you can wait until we:
- Upload the files in a ftp server and provide a script (such as get_data) that downloads them and creates the necessary dir structure
OR
- Change the pypackage so you can compute them or use another CNN architecture as needed (this is the final goal, the modular package that we will try to post it on PIP for an easy installation).

Thank you very much for your interest in this project!
Issey

**Comment by Innovator545** [comment]
Hi Issey,

Thanks for your elaborate reply !! I really appreciate a lot.

For Now, It would be great to have all the needed files (especially All other required files other than complete github setup)  along with steps to execute them. My email id is preetdhanoa@gmail.com. It would be nice if you can email me or share via dropbox, whichever way is convenient for you.

My main intention is to use ** ONLY My own Images** (which are totally different from VQA images) throughout the complete process like generation of train_ImageNet_FisherVectors.mat file etc and for all other processing everywhere else in the Algorithm.

I wish to successfully do the compile, training, validation and testing for my images.

I would also be very interested in your planned future releases - get_data script release and/OR pypackage update release.

Also, My Current directory structure is like this. Just attaching it for if you might have any inputs for placing new files that you will provide.
![my_vqa_setup_structure](https://cloud.githubusercontent.com/assets/20482225/16924131/ae0c172c-4ceb-11e6-8cf7-76e779f81cec.jpg)

Thanks again for your help.

Warm Regards,
Preetinder Singh

**Comment by xavigiro** [comment]
Our server at the UPC university can host those files and publish them. No problem. We will handle it and get back to you in this same isseu.

**Comment by Innovator545** [comment]
Great. Thank You very much Sir !!

**Comment by issey173** [comment]
As @xavigiro said, we will post these missing files in our servers. With that you will be able to repeat our exact same experiments, but you will not be able to use custom images. The first stages of the image branch are provided from a collaboration group we work with, and they are implemented in Cafe.

These project is quite focused on VQA Challenge CVPR 2016 and taking into account those precomputed visual features. We are developing a new project to address VQA as a generic task and we will implement the whole architecture there. This way you will be able to use our package to use or create models for VQA independently to the dataset and you will be able to use your own images.
The repo is private until we build a basic skeleton, we will post the link in this repo once we publish it.

Thanks again for your interest

**Comment by Innovator545** [comment]
Thanks for the update Issey . That sounds good !
In the mean time, i ll continue with my research on Fisher vector understanding and generation.

Being new to Visual QA Area, I am very interested in your work. For my learning, I am awaiting to have your files being uploaded and would like to repeat your exact experiments. I wish to learn a lot from those experiments. Thanks! 

GENERIC VQA Package for using with any image dataset will be a great Research tool. I will wait for the release. Thanks and Best wishes for this task.

**Comment by issey173** [comment]
Hi @Innovator545 ,

Here you can find the missing files:

- https://imatge.upc.edu/web/sites/default/files/projects/deeplearning/public/2016-vqa-cvpr/test_ImageNet_FisherVectors.mat
- https://imatge.upc.edu/web/sites/default/files/projects/deeplearning/public/2016-vqa-cvpr/test_list.txt
- https://imatge.upc.edu/web/sites/default/files/projects/deeplearning/public/2016-vqa-cvpr/train_ImageNet_FisherVectors.mat
- https://imatge.upc.edu/web/sites/default/files/projects/deeplearning/public/2016-vqa-cvpr/train_list.txt
- https://imatge.upc.edu/web/sites/default/files/projects/deeplearning/public/2016-vqa-cvpr/train_ImageNet_FisherVectors.mat
- https://imatge.upc.edu/web/sites/default/files/projects/deeplearning/public/2016-vqa-cvpr/train_list.txt

You only need to place these files in `project_root/data/preprocessed/features/` in order to work if you do not want to modify the scripts. 

Hopefully in a couple of weeks we will publish the generic package. 

Best,
Issey

**Comment by Innovator545** [comment]
Nice work. Thanks a lot for all the files and info.
I will start my experiments.

Thanks for the update on generic package as well.

Thanks and Regards,
Preetinder Singh

**Comment by Innovator545** [comment]
Greetings UPC University Team !!

Hope All the UPC University team is doing well.
I am able to play around a bit with Visual QA and it looks quite promising.

Kindly Suggest if  any possibility of generic package release might be there sometime.

Thanks and Regards,
Preetinder Singh

**Comment by issey173** [comment]
Hi @Innovator545 !

We are just working on that, but we are building a project following the best common practices, adding tests, docs, CI.... We want to be sure that the project that we will open-source is generic and easy to use/install, so we are spending more time on these things, it's not just the features of the package itself. 

As mentioned previously, whenever we have a public version we will add some notification in this repo.

Bests,
Issey

**Comment by Innovator545** [comment]
Thank You very much !!

Thanks and Regards,
Preetinder Singh

**Comment by issey173** [comment]
@Innovator545 just want to mention that we have release a Deep Learning abstract framework in beta version. If you are interested in give it a try: https://github.com/issey173/DeepFramework

Thanks!

**Comment by Innovator545** [comment]
Congratulations & Thanks UPC University Team for the framework beta release!!
We will give it a try & provide any important feedback.
Thanks again !!

Thanks & Regards,
Preetinder Singh
